[versions]

#noinspection UnusedVersionCatalogEntry
versionCode = "41"

# https://developer.android.com/tools/releases/build-tools
#noinspection UnusedVersionCatalogEntry
buildToolsVersion = "36.1.0"

# https://developer.android.com/tools/releases/platforms
#noinspection UnusedVersionCatalogEntry
compileSdk = "36"
#noinspection UnusedVersionCatalogEntry
minSdk = "28"

[libraries]

# https://mvnrepository.com/artifact/com.mikepenz/aboutlibraries
aboutlibraries = { module = "com.mikepenz:aboutlibraries", version = "13.2.1" }

# https://mvnrepository.com/artifact/androidx.test/runner
androidTest-runner = { module = "androidx.test:runner", version = "1.7.0" }

# https://mvnrepository.com/artifact/androidx.test.ext/junit-ktx
androidTest-junit = { module = "androidx.test.ext:junit-ktx", version = "1.3.0" }

# https://mvnrepository.com/artifact/androidx.test.uiautomator/uiautomator
androidTest-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version = "2.3.0" }

# https://mvnrepository.com/artifact/junit/junit
test-junit = { module = "junit:junit", version = "4.13.2" }

[plugins]

# https://mvnrepository.com/artifact/com.android.tools.build/gradle
android-application = { id = "com.android.application", version = "9.0.0" }
android-library = { id = "com.android.library", version = "9.0.0" }

# https://mvnrepository.com/artifact/com.mikepenz.aboutlibraries.plugin/com.mikepenz.aboutlibraries.plugin.gradle.plugin
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version = "13.2.1" }

# https://mvnrepository.com/artifact/org.ajoberstar.grgit/org.ajoberstar.grgit.gradle.plugin
grgit = { id = "org.ajoberstar.grgit", version = "5.3.3" }

# https://mvnrepository.com/artifact/com.github.breadmoirai.github-release/com.github.breadmoirai.github-release.gradle.plugin
github-release = { id = "com.github.breadmoirai.github-release", version = "2.5.2" }
